object TokyoMetro {
  val stations: List[Station] = List(
    Station(nameKanji="代々木上原", nameKana="よよぎうえはら", name="yoyogiuehara", line="千代田線"),
    Station(nameKanji="代々木公園", nameKana="よよぎこうえん", name="yoyogikouen", line="千代田線"),
    Station(nameKanji="明治神宮前", nameKana="めいじじんぐうまえ", name="meijijinguumae", line="千代田線"),
    Station(nameKanji="表参道", nameKana="おもてさんどう", name="omotesandou", line="千代田線"),
    Station(nameKanji="乃木坂", nameKana="のぎざか", name="nogizaka", line="千代田線"),
    Station(nameKanji="赤坂", nameKana="あかさか", name="akasaka", line="千代田線"),
    Station(nameKanji="国会議事堂前", nameKana="こっかいぎじどうまえ", name="kokkaigijidoumae", line="千代田線"),
    Station(nameKanji="霞ヶ関", nameKana="かすみがせき", name="kasumigaseki", line="千代田線"),
    Station(nameKanji="日比谷", nameKana="ひびや", name="hibiya", line="千代田線"),
    Station(nameKanji="二重橋前", nameKana="にじゅうばしまえ", name="nijuubasimae", line="千代田線"),
    Station(nameKanji="大手町", nameKana="おおてまち", name="otemachi", line="千代田線"),
    Station(nameKanji="新御茶ノ水", nameKana="しんおちゃのみず", name="shin-ochanomizu", line="千代田線"),
    Station(nameKanji="湯島", nameKana="ゆしま", name="yushima", line="千代田線"),
    Station(nameKanji="根津", nameKana="ねづ", name="nedu", line="千代田線"),
    Station(nameKanji="千駄木", nameKana="せんだぎ", name="sendagi", line="千代田線"),
    Station(nameKanji="西日暮里", nameKana="にしにっぽり", name="nishinippori", line="千代田線"),
    Station(nameKanji="町屋", nameKana="まちや", name="machiya", line="千代田線"),
    Station(nameKanji="北千住", nameKana="きたせんじゅ", name="kitasenjyu", line="千代田線"),
    Station(nameKanji="綾瀬", nameKana="あやせ", name="ayase", line="千代田線"),
    Station(nameKanji="北綾瀬", nameKana="きたあやせ", name="kitaayase", line="千代田線"),
    Station(nameKanji="浅草", nameKana="あさくさ", name="asakusa", line="銀座線"),
    Station(nameKanji="田原町", nameKana="たわらまち", name="tawaramachi", line="銀座線"),
    Station(nameKanji="稲荷町", nameKana="いなりちょう", name="inaricho", line="銀座線"),
    Station(nameKanji="上野", nameKana="うえの", name="ueno", line="銀座線"),
    Station(nameKanji="上野広小路", nameKana="うえのひろこうじ", name="uenohirokoji", line="銀座線"),
    Station(nameKanji="末広町", nameKana="すえひろちょう", name="suehirocho", line="銀座線"),
    Station(nameKanji="神田", nameKana="かんだ", name="kanda", line="銀座線"),
    Station(nameKanji="三越前", nameKana="みつこしまえ", name="mitsukoshimae", line="銀座線"),
    Station(nameKanji="日本橋", nameKana="にほんばし", name="nihonbashi", line="銀座線"),
    Station(nameKanji="京橋", nameKana="きょうばし", name="kyobashi", line="銀座線"),
    Station(nameKanji="銀座", nameKana="ぎんざ", name="ginza", line="銀座線"),
    Station(nameKanji="新橋", nameKana="しんばし", name="shinbashi", line="銀座線"),
    Station(nameKanji="虎ノ門", nameKana="とらのもん", name="toranomon", line="銀座線"),
    Station(nameKanji="溜池山王", nameKana="ためいけさんのう", name="tameikesannou", line="銀座線"),
    Station(nameKanji="赤坂見附", nameKana="あかさかみつけ", name="akasakamitsuke", line="銀座線"),
    Station(nameKanji="青山一丁目", nameKana="あおやまいっちょうめ", name="aoyamaicchome", line="銀座線"),
    Station(nameKanji="外苑前", nameKana="がいえんまえ", name="gaienmae", line="銀座線"),
    Station(nameKanji="表参道", nameKana="おもてさんどう", name="omotesando", line="銀座線"),
    Station(nameKanji="渋谷", nameKana="しぶや", name="shibuya", line="銀座線"),
    Station(nameKanji="渋谷", nameKana="しぶや", name="shibuya", line="半蔵門線"),
    Station(nameKanji="表参道", nameKana="おもてさんどう", name="omotesandou", line="半蔵門線"),
    Station(nameKanji="青山一丁目", nameKana="あおやまいっちょうめ", name="aoyama-itchome", line="半蔵門線"),
    Station(nameKanji="永田町", nameKana="ながたちょう", name="nagatacho", line="半蔵門線"),
    Station(nameKanji="半蔵門", nameKana="はんぞうもん", name="hanzomon", line="半蔵門線"),
    Station(nameKanji="九段下", nameKana="くだんした", name="kudanshita", line="半蔵門線"),
    Station(nameKanji="神保町", nameKana="じんぼうちょう", name="jinbocho", line="半蔵門線"),
    Station(nameKanji="大手町", nameKana="おおてまち", name="otemachi", line="半蔵門線"),
    Station(nameKanji="三越前", nameKana="みつこしまえ", name="mitsukoshimae", line="半蔵門線"),
    Station(nameKanji="水天宮前", nameKana="すいてんぐうまえ", name="suitengumae", line="半蔵門線"),
    Station(nameKanji="清澄白河", nameKana="きよすみしらかわ", name="kiyosumi-shirakawa", line="半蔵門線"),
    Station(nameKanji="住吉", nameKana="すみよし", name="sumiyoshi", line="半蔵門線"),
    Station(nameKanji="錦糸町", nameKana="きんしちょう", name="kinshicho", line="半蔵門線"),
    Station(nameKanji="押上", nameKana="おしあげ", name="oshiage", line="半蔵門線"),
    Station(nameKanji="中目黒", nameKana="なかめぐろ", name="nakameguro", line="日比谷線"),
    Station(nameKanji="恵比寿", nameKana="えびす", name="ebisu", line="日比谷線"),
    Station(nameKanji="広尾", nameKana="ひろお", name="hiro", line="日比谷線"),
    Station(nameKanji="六本木", nameKana="ろっぽんぎ", name="roppongi", line="日比谷線"),
    Station(nameKanji="神谷町", nameKana="かみやちょう", name="kamiyacho", line="日比谷線"),
    Station(nameKanji="霞ヶ関", nameKana="かすみがせき", name="kasumigaseki", line="日比谷線"),
    Station(nameKanji="日比谷", nameKana="ひびや", name="hibiya", line="日比谷線"),
    Station(nameKanji="銀座", nameKana="ぎんざ", name="ginza", line="日比谷線"),
    Station(nameKanji="東銀座", nameKana="ひがしぎんざ", name="higashiginza", line="日比谷線"),
    Station(nameKanji="築地", nameKana="つきじ", name="tsukiji", line="日比谷線"),
    Station(nameKanji="八丁堀", nameKana="はっちょうぼり", name="hacchobori", line="日比谷線"),
    Station(nameKanji="茅場町", nameKana="かやばちょう", name="kayabacho", line="日比谷線"),
    Station(nameKanji="人形町", nameKana="にんぎょうちょう", name="ningyomachi", line="日比谷線"),
    Station(nameKanji="小伝馬町", nameKana="こでんまちょう", name="kodemmacho", line="日比谷線"),
    Station(nameKanji="秋葉原", nameKana="あきはばら", name="akihabara", line="日比谷線"),
    Station(nameKanji="仲御徒町", nameKana="なかおかちまち", name="nakaokachimachi", line="日比谷線"),
    Station(nameKanji="上野", nameKana="うえの", name="ueno", line="日比谷線"),
    Station(nameKanji="入谷", nameKana="いりや", name="iriya", line="日比谷線"),
    Station(nameKanji="三ノ輪", nameKana="みのわ", name="minowa", line="日比谷線"),
    Station(nameKanji="南千住", nameKana="みなみせんじゅ", name="minamisenju", line="日比谷線"),
    Station(nameKanji="北千住", nameKana="きたせんじゅ", name="kitasenju", line="日比谷線"),
    Station(nameKanji="池袋", nameKana="いけぶくろ", name="ikebukuro", line="丸ノ内線"),
    Station(nameKanji="新大塚", nameKana="しんおおつか", name="shinotsuka", line="丸ノ内線"),
    Station(nameKanji="茗荷谷", nameKana="みょうがだに", name="myogadani", line="丸ノ内線"),
    Station(nameKanji="後楽園", nameKana="こうらくえん", name="korakuen", line="丸ノ内線"),
    Station(nameKanji="本郷三丁目", nameKana="ほんごうさんちょうめ", name="hongosanchome", line="丸ノ内線"),
    Station(nameKanji="御茶ノ水", nameKana="おちゃのみず", name="ochanomizu", line="丸ノ内線"),
    Station(nameKanji="淡路町", nameKana="あわじちょう", name="awajicho", line="丸ノ内線"),
    Station(nameKanji="大手町", nameKana="おおてまち", name="otemachi", line="丸ノ内線"),
    Station(nameKanji="東京", nameKana="とうきょう", name="tokyo", line="丸ノ内線"),
    Station(nameKanji="銀座", nameKana="ぎんざ", name="ginza", line="丸ノ内線"),
    Station(nameKanji="霞ヶ関", nameKana="かすみがせき", name="kasumigaseki", line="丸ノ内線"),
    Station(nameKanji="国会議事堂前", nameKana="こっかいぎじどうまえ", name="kokkaigijidomae", line="丸ノ内線"),
    Station(nameKanji="赤坂見附", nameKana="あかさかみつけ", name="akasakamitsuke", line="丸ノ内線"),
    Station(nameKanji="四ツ谷", nameKana="よつや", name="yotsuya", line="丸ノ内線"),
    Station(nameKanji="四谷三丁目", nameKana="よつやさんちょうめ", name="yotsuyasanchome", line="丸ノ内線"),
    Station(nameKanji="新宿御苑前", nameKana="しんじゅくぎょえんまえ", name="shinjuku-gyoemmae", line="丸ノ内線"),
    Station(nameKanji="新宿三丁目", nameKana="しんじゅくさんちょうめ", name="shinjuku-sanchome", line="丸ノ内線"),
    Station(nameKanji="新宿", nameKana="しんじゅく", name="shinjuku", line="丸ノ内線"),
    Station(nameKanji="西新宿", nameKana="にししんじゅく", name="nishi-shinjuku", line="丸ノ内線"),
    Station(nameKanji="中野坂上", nameKana="なかのさかうえ", name="nakano-sakaue", line="丸ノ内線"),
    Station(nameKanji="新中野", nameKana="しんなかの", name="shin-nakano", line="丸ノ内線"),
    Station(nameKanji="東高円寺", nameKana="ひがしこうえんじ", name="higashi-koenji", line="丸ノ内線"),
    Station(nameKanji="新高円寺", nameKana="しんこうえんじ", name="shin-koenji", line="丸ノ内線"),
    Station(nameKanji="南阿佐ヶ谷", nameKana="みなみあさがや", name="minami-asagaya", line="丸ノ内線"),
    Station(nameKanji="荻窪", nameKana="おぎくぼ", name="ogikubo", line="丸ノ内線"),
    Station(nameKanji="中野新橋", nameKana="なかのしんばし", name="nakano-shimbashi", line="丸ノ内線"),
    Station(nameKanji="中野富士見町", nameKana="なかのふじみちょう", name="nakano-fujimicho", line="丸ノ内線"),
    Station(nameKanji="方南町", nameKana="ほうなんちょう", name="honancho", line="丸ノ内線"),
    Station(nameKanji="四ツ谷", nameKana="よつや", name="yotsuya", line="南北線"),
    Station(nameKanji="永田町", nameKana="ながたちょう", name="nagatacho", line="南北線"),
    Station(nameKanji="溜池山王", nameKana="ためいけさんのう", name="tameikesanno", line="南北線"),
    Station(nameKanji="六本木一丁目", nameKana="ろっぽんぎいっちょうめ", name="roppongiitchome", line="南北線"),
    Station(nameKanji="麻布十番", nameKana="あざぶじゅうばん", name="azabujuban", line="南北線"),
    Station(nameKanji="白金高輪", nameKana="しろかねたかなわ", name="shirokanetanameKanawa", line="南北線"),
    Station(nameKanji="白金台", nameKana="しろかねだい", name="shirokanedai", line="南北線"),
    Station(nameKanji="目黒", nameKana="めぐろ", name="meguro", line="南北線"),
    Station(nameKanji="市ヶ谷", nameKana="いちがや", name="ichigaya", line="南北線"),
    Station(nameKanji="飯田橋", nameKana="いいだばし", name="idabashi", line="南北線"),
    Station(nameKanji="後楽園", nameKana="こうらくえん", name="korakuen", line="南北線"),
    Station(nameKanji="東大前", nameKana="とうだいまえ", name="todaimae", line="南北線"),
    Station(nameKanji="本駒込", nameKana="ほんこまごめ", name="honkomagome", line="南北線"),
    Station(nameKanji="駒込", nameKana="こまごめ", name="komagome", line="南北線"),
    Station(nameKanji="西ヶ原", nameKana="にしがはら", name="nishigahara", line="南北線"),
    Station(nameKanji="王子", nameKana="おうじ", name="oji", line="南北線"),
    Station(nameKanji="王子神谷", nameKana="おうじかみや", name="ojikamiya", line="南北線"),
    Station(nameKanji="志茂", nameKana="しも", name="shimo", line="南北線"),
    Station(nameKanji="赤羽岩淵", nameKana="あかばねいわぶち", name="akabaneiwabuchi", line="南北線"),
    Station(nameKanji="西船橋", nameKana="にしふなばし", name="nishi-funabashi", line="東西線"),
    Station(nameKanji="原木中山", nameKana="ばらきなかやま", name="baraki-nakayama", line="東西線"),
    Station(nameKanji="妙典", nameKana="みょうでん", name="myoden", line="東西線"),
    Station(nameKanji="行徳", nameKana="ぎょうとく", name="gyotoku", line="東西線"),
    Station(nameKanji="南行徳", nameKana="みなみぎょうとく", name="minami-gyotoku", line="東西線"),
    Station(nameKanji="浦安", nameKana="うらやす", name="urayasu", line="東西線"),
    Station(nameKanji="葛西", nameKana="かさい", name="kasai", line="東西線"),
    Station(nameKanji="西葛西", nameKana="にしかさい", name="nishi-kasai", line="東西線"),
    Station(nameKanji="南砂町", nameKana="みなみすなまち", name="minami-sunamachi", line="東西線"),
    Station(nameKanji="東陽町", nameKana="とうようちょう", name="touyoucho", line="東西線"),
    Station(nameKanji="木場", nameKana="きば", name="kiba", line="東西線"),
    Station(nameKanji="門前仲町", nameKana="もんぜんなかちょう", name="monzen-nakacho", line="東西線"),
    Station(nameKanji="茅場町", nameKana="かやばちょう", name="kayabacho", line="東西線"),
    Station(nameKanji="日本橋", nameKana="にほんばし", name="nihonbashi", line="東西線"),
    Station(nameKanji="大手町", nameKana="おおてまち", name="otemachi", line="東西線"),
    Station(nameKanji="竹橋", nameKana="たけばし", name="takebashi", line="東西線"),
    Station(nameKanji="九段下", nameKana="くだんした", name="kudanshita", line="東西線"),
    Station(nameKanji="飯田橋", nameKana="いいだばし", name="iidabashi", line="東西線"),
    Station(nameKanji="神楽坂", nameKana="かぐらざか", name="kagurazaka", line="東西線"),
    Station(nameKanji="早稲田", nameKana="わせだ", name="waseda", line="東西線"),
    Station(nameKanji="高田馬場", nameKana="たかだのばば", name="takadanobaba", line="東西線"),
    Station(nameKanji="落合", nameKana="おちあい", name="ochiai", line="東西線"),
    Station(nameKanji="中野", nameKana="なかの", name="nakano", line="東西線"),
    Station(name="shinkiba", nameKana="しんきば", nameKanji="新木場", line="有楽町線"),
    Station(name="tatsumi", nameKana="たつみ", nameKanji="辰巳", line="有楽町線"),
    Station(name="toyosu", nameKana="とよす", nameKanji="豊洲", line="有楽町線"),
    Station(name="tsukishima", nameKana="つきしま", nameKanji="月島", line="有楽町線"),
    Station(name="shintomityou", nameKana="しんとみちょう", nameKanji="新富町", line="有楽町線"),
    Station(name="ginzaittyoume", nameKana="ぎんざいっちょうめ", nameKanji="銀座一丁目", line="有楽町線"),
    Station(name="yuurakutyou", nameKana="ゆうらくちょう", nameKanji="有楽町", line="有楽町線"),
    Station(name="sakuradamon", nameKana="さくらだもん", nameKanji="桜田門", line="有楽町線"),
    Station(name="nagatacho", nameKana="ながたちょう", nameKanji="永田町", line="有楽町線"),
    Station(name="koujimachi", nameKana="こうじまち", nameKanji="麹町", line="有楽町線"),
    Station(name="ichigaya", nameKana="いちがや", nameKanji="市ヶ谷", line="有楽町線"),
    Station(name="iidabashi", nameKana="いいだばし", nameKanji="飯田橋", line="有楽町線"),
    Station(nameKanji="江戸川橋", nameKana="えどがわばし", name="edogawabasi", line="有楽町線"),
    Station(nameKanji="護国寺", nameKana="ごこくじ", name="gokokuji", line="有楽町線"),
    Station(nameKanji="東池袋", nameKana="ひがしいけぶくろ", name="higasiikebukuro", line="有楽町線"),
    Station(nameKanji="池袋", nameKana="いけぶくろ", name="ikebukuro", line="有楽町線"),
    Station(nameKanji="要町", nameKana="かなめちょう", name="nameKanametyou", line="有楽町線"),
    Station(nameKanji="千川", nameKana="せんかわ", name="senkawa", line="有楽町線"),
    Station(nameKanji="小竹向原", nameKana="こたけむかいはら", name="kotakemukaihara", line="有楽町線"),
    Station(nameKanji="氷川台", nameKana="ひかわだい", name="hikawadai", line="有楽町線"),
    Station(nameKanji="平和台", nameKana="へいわだい", name="heiwadai", line="有楽町線"),
    Station(nameKanji="営団赤塚", nameKana="えいだんあかつか", name="eidanakakuka", line="有楽町線"),
    Station(nameKanji="営団成増", nameKana="えいだんなります", name="eidannarimasu", line="有楽町線"),
    Station(nameKanji="和光市", nameKana="わこうし", name="wakousi", line="有楽町線")
  )

  val distances: List[Distance] = List(
    Distance(from="代々木上原", to="代々木公園", line="千代田線", distance=1.0, time=2),
    Distance(from="代々木公園", to="明治神宮前", line="千代田線", distance=1.2, time=2),
    Distance(from="明治神宮前", to="表参道", line="千代田線", distance=0.9, time=2),
    Distance(from="表参道", to="乃木坂", line="千代田線", distance=1.4, time=3),
    Distance(from="乃木坂", to="赤坂", line="千代田線", distance=1.1, time=2),
    Distance(from="赤坂", to="国会議事堂前", line="千代田線", distance=0.8, time=1),
    Distance(from="国会議事堂前", to="霞ヶ関", line="千代田線", distance=0.7, time=1),
    Distance(from="霞ヶ関", to="日比谷", line="千代田線", distance=1.2, time=2),
    Distance(from="日比谷", to="二重橋前", line="千代田線", distance=0.7, time=1),
    Distance(from="二重橋前", to="大手町", line="千代田線", distance=0.7, time=1),
    Distance(from="大手町", to="新御茶ノ水", line="千代田線", distance=1.3, time=2),
    Distance(from="新御茶ノ水", to="湯島", line="千代田線", distance=1.2, time=2),
    Distance(from="湯島", to="根津", line="千代田線", distance=1.2, time=2),
    Distance(from="根津", to="千駄木", line="千代田線", distance=1.0, time=2),
    Distance(from="千駄木", to="西日暮里", line="千代田線", distance=0.9, time=1),
    Distance(from="西日暮里", to="町屋", line="千代田線", distance=1.7, time=2),
    Distance(from="町屋", to="北千住", line="千代田線", distance=2.6, time=3),
    Distance(from="北千住", to="綾瀬", line="千代田線", distance=2.5, time=3),
    Distance(from="綾瀬", to="北綾瀬", line="千代田線", distance=2.1, time=4),
    Distance(from="浅草", to="田原町", line="銀座線", distance=0.8, time=2),
    Distance(from="田原町", to="稲荷町", line="銀座線", distance=0.7, time=1),
    Distance(from="稲荷町", to="上野", line="銀座線", distance=0.7, time=2),
    Distance(from="上野", to="上野広小路", line="銀座線", distance=0.5, time=2),
    Distance(from="上野広小路", to="末広町", line="銀座線", distance=0.6, time=1),
    Distance(from="末広町", to="神田", line="銀座線", distance=1.1, time=2),
    Distance(from="神田", to="三越前", line="銀座線", distance=0.7, time=1),
    Distance(from="三越前", to="日本橋", line="銀座線", distance=0.6, time=2),
    Distance(from="日本橋", to="京橋", line="銀座線", distance=0.7, time=2),
    Distance(from="京橋", to="銀座", line="銀座線", distance=0.7, time=1),
    Distance(from="銀座", to="新橋", line="銀座線", distance=0.9, time=2),
    Distance(from="新橋", to="虎ノ門", line="銀座線", distance=0.8, time=2),
    Distance(from="虎ノ門", to="溜池山王", line="銀座線", distance=0.6, time=2),
    Distance(from="溜池山王", to="赤坂見附", line="銀座線", distance=0.9, time=2),
    Distance(from="赤坂見附", to="青山一丁目", line="銀座線", distance=1.3, time=2),
    Distance(from="青山一丁目", to="外苑前", line="銀座線", distance=0.7, time=2),
    Distance(from="外苑前", to="表参道", line="銀座線", distance=0.7, time=1),
    Distance(from="表参道", to="渋谷", line="銀座線", distance=1.3, time=1),
    Distance(from="渋谷", to="表参道", line="半蔵門線", distance=1.3, time=2),
    Distance(from="表参道", to="青山一丁目", line="半蔵門線", distance=1.4, time=2),
    Distance(from="青山一丁目", to="永田町", line="半蔵門線", distance=1.3, time=2),
    Distance(from="永田町", to="半蔵門", line="半蔵門線", distance=1.0, time=2),
    Distance(from="半蔵門", to="九段下", line="半蔵門線", distance=1.6, time=2),
    Distance(from="九段下", to="神保町", line="半蔵門線", distance=0.4, time=1),
    Distance(from="神保町", to="大手町", line="半蔵門線", distance=1.7, time=3),
    Distance(from="大手町", to="三越前", line="半蔵門線", distance=0.7, time=1),
    Distance(from="三越前", to="水天宮前", line="半蔵門線", distance=1.3, time=2),
    Distance(from="水天宮前", to="清澄白河", line="半蔵門線", distance=1.7, time=3),
    Distance(from="清澄白河", to="住吉", line="半蔵門線", distance=1.9, time=3),
    Distance(from="住吉", to="錦糸町", line="半蔵門線", distance=1.0, time=2),
    Distance(from="錦糸町", to="押上", line="半蔵門線", distance=1.4, time=2),
    Distance(from="中目黒", to="恵比寿", line="日比谷線", distance=1.0, time=2),
    Distance(from="恵比寿", to="広尾", line="日比谷線", distance=1.5, time=3),
    Distance(from="広尾", to="六本木", line="日比谷線", distance=1.7, time=3),
    Distance(from="六本木", to="神谷町", line="日比谷線", distance=1.5, time=3),
    Distance(from="神谷町", to="霞ヶ関", line="日比谷線", distance=1.3, time=2),
    Distance(from="霞ヶ関", to="日比谷", line="日比谷線", distance=1.2, time=2),
    Distance(from="日比谷", to="銀座", line="日比谷線", distance=0.4, time=1),
    Distance(from="銀座", to="東銀座", line="日比谷線", distance=0.4, time=1),
    Distance(from="東銀座", to="築地", line="日比谷線", distance=0.6, time=2),
    Distance(from="築地", to="八丁堀", line="日比谷線", distance=1.0, time=2),
    Distance(from="八丁堀", to="茅場町", line="日比谷線", distance=0.5, time=1),
    Distance(from="茅場町", to="人形町", line="日比谷線", distance=0.9, time=2),
    Distance(from="人形町", to="小伝馬町", line="日比谷線", distance=0.6, time=1),
    Distance(from="小伝馬町", to="秋葉原", line="日比谷線", distance=0.9, time=2),
    Distance(from="秋葉原", to="仲御徒町", line="日比谷線", distance=1.0, time=1),
    Distance(from="仲御徒町", to="上野", line="日比谷線", distance=0.5, time=1),
    Distance(from="上野", to="入谷", line="日比谷線", distance=1.2, time=2),
    Distance(from="入谷", to="三ノ輪", line="日比谷線", distance=1.2, time=2),
    Distance(from="三ノ輪", to="南千住", line="日比谷線", distance=0.8, time=2),
    Distance(from="南千住", to="北千住", line="日比谷線", distance=1.8, time=3),
    Distance(from="池袋", to="新大塚", line="丸ノ内線", distance=1.8, time=3),
    Distance(from="新大塚", to="茗荷谷", line="丸ノ内線", distance=1.2, time=2),
    Distance(from="茗荷谷", to="後楽園", line="丸ノ内線", distance=1.8, time=2),
    Distance(from="後楽園", to="本郷三丁目", line="丸ノ内線", distance=0.8, time=1),
    Distance(from="本郷三丁目", to="御茶ノ水", line="丸ノ内線", distance=0.8, time=1),
    Distance(from="御茶ノ水", to="淡路町", line="丸ノ内線", distance=0.8, time=1),
    Distance(from="淡路町", to="大手町", line="丸ノ内線", distance=0.9, time=2),
    Distance(from="大手町", to="東京", line="丸ノ内線", distance=0.6, time=1),
    Distance(from="東京", to="銀座", line="丸ノ内線", distance=1.1, time=2),
    Distance(from="銀座", to="霞ヶ関", line="丸ノ内線", distance=1.0, time=2),
    Distance(from="霞ヶ関", to="国会議事堂前", line="丸ノ内線", distance=0.7, time=1),
    Distance(from="国会議事堂前", to="赤坂見附", line="丸ノ内線", distance=0.9, time=2),
    Distance(from="赤坂見附", to="四ツ谷", line="丸ノ内線", distance=1.3, time=2),
    Distance(from="四ツ谷", to="四谷三丁目", line="丸ノ内線", distance=1.0, time=2),
    Distance(from="四谷三丁目", to="新宿御苑前", line="丸ノ内線", distance=0.9, time=1),
    Distance(from="新宿御苑前", to="新宿三丁目", line="丸ノ内線", distance=0.7, time=1),
    Distance(from="新宿三丁目", to="新宿", line="丸ノ内線", distance=0.3, time=1),
    Distance(from="新宿", to="西新宿", line="丸ノ内線", distance=0.8, time=1),
    Distance(from="西新宿", to="中野坂上", line="丸ノ内線", distance=1.1, time=2),
    Distance(from="中野坂上", to="新中野", line="丸ノ内線", distance=1.1, time=2),
    Distance(from="新中野", to="東高円寺", line="丸ノ内線", distance=1.0, time=1),
    Distance(from="東高円寺", to="新高円寺", line="丸ノ内線", distance=0.9, time=1),
    Distance(from="新高円寺", to="南阿佐ヶ谷", line="丸ノ内線", distance=1.2, time=2),
    Distance(from="南阿佐ヶ谷", to="荻窪", line="丸ノ内線", distance=1.5, time=2),
    Distance(from="中野坂上", to="中野新橋", line="丸ノ内線", distance=1.3, time=2),
    Distance(from="中野新橋", to="中野富士見町", line="丸ノ内線", distance=0.6, time=1),
    Distance(from="中野富士見町", to="方南町", line="丸ノ内線", distance=1.3, time=2),
    Distance(from="市ヶ谷", to="四ツ谷", line="南北線", distance=1.0, time=2),
    Distance(from="四ツ谷", to="永田町", line="南北線", distance=1.3, time=3),
    Distance(from="永田町", to="溜池山王", line="南北線", distance=0.9, time=1),
    Distance(from="溜池山王", to="六本木一丁目", line="南北線", distance=0.9, time=2),
    Distance(from="六本木一丁目", to="麻布十番", line="南北線", distance=1.2, time=2),
    Distance(from="麻布十番", to="白金高輪", line="南北線", distance=1.3, time=2),
    Distance(from="白金高輪", to="白金台", line="南北線", distance=1.0, time=2),
    Distance(from="白金台", to="目黒", line="南北線", distance=1.3, time=2),
    Distance(from="市ヶ谷", to="飯田橋", line="南北線", distance=1.1 , time=2),
    Distance(from="飯田橋", to="後楽園", line="南北線", distance=1.4 , time=2),
    Distance(from="後楽園", to="東大前", line="南北線", distance=1.3 , time=3),
    Distance(from="東大前", to="本駒込", line="南北線", distance=0.9 , time=2),
    Distance(from="本駒込", to="駒込", line="南北線", distance=1.4, time=2),
    Distance(from="駒込", to="西ヶ原", line="南北線", distance=1.4, time=2),
    Distance(from="西ヶ原", to="王子", line="南北線", distance=1.0, time=2),
    Distance(from="王子", to="王子神谷", line="南北線", distance=1.2, time=2),
    Distance(from="王子神谷", to="志茂", line="南北線", distance=1.6, time=3),
    Distance(from="志茂", to="赤羽岩淵", line="南北線", distance=1.1, time=2),
    Distance(from="西船橋" , to="原木中山", line="東西線", distance=1.9, time=3),
    Distance(from="原木中山", to="妙典", line="東西線", distance=2.1 , time=2),
    Distance(from="妙典", to="行徳", line="東西線", distance=1.3 , time=2),
    Distance(from="行徳", to="南行徳", line="東西線", distance=1.5 , time=2),
    Distance(from="南行徳", to="浦安" , line="東西線", distance=1.2 , time=2),
    Distance(from="浦安" , to="葛西", line="東西線", distance=1.9 , time=2),
    Distance(from="葛西", to="西葛西", line="東西線", distance=1.2 , time=2),
    Distance(from="西葛西", to="南砂町", line="東西線", distance=2.7 , time=2),
    Distance(from="南砂町", to="東陽町", line="東西線", distance=1.2 , time=2),
    Distance(from="東陽町", to="木場" , line="東西線", distance=0.9 , time=1),
    Distance(from="木場", to="門前仲町", line="東西線", distance=1.1 , time=1),
    Distance(from="門前仲町", to="茅場町", line="東西線", distance=1.8 , time=2),
    Distance(from="茅場町", to="日本橋", line="東西線", distance=0.5 , time=1),
    Distance(from="日本橋", to="大手町", line="東西線", distance=0.8 , time=1),
    Distance(from="大手町", to="竹橋", line="東西線", distance=1.0, time=2),
    Distance(from="竹橋", to="九段下", line="東西線", distance=1.0, time=1),
    Distance(from="九段下", to="飯田橋", line="東西線", distance=0.7, time=1),
    Distance(from="飯田橋", to="神楽坂", line="東西線", distance=1.2, time=2),
    Distance(from="神楽坂", to="早稲田", line="東西線", distance=1.2, time=2),
    Distance(from="早稲田", to="高田馬場", line="東西線", distance=1.7, time=3),
    Distance(from="高田馬場", to="落合", line="東西線", distance=1.9, time=3),
    Distance(from="落合", to="中野", line="東西線", distance=2.0, time=3),
    Distance(from="新木場", to="辰巳", line="有楽町線", distance=1.5, time=2),
    Distance(from="辰巳", to="豊洲", line="有楽町線", distance=1.7, time=2),
    Distance(from="豊洲", to="月島", line="有楽町線", distance=1.4, time=2),
    Distance(from="月島", to="新富町", line="有楽町線", distance=1.3, time=2),
    Distance(from="新富町", to="銀座一丁目", line="有楽町線", distance=0.7, time=1),
    Distance(from="銀座一丁目", to="有楽町", line="有楽町線", distance=0.5, time=1),
    Distance(from="有楽町", to="桜田門", line="有楽町線", distance=1.0, time=1),
    Distance(from="桜田門", to="永田町", line="有楽町線", distance=0.9, time=2),
    Distance(from="永田町", to="麹町", line="有楽町線", distance=0.9, time=1),
    Distance(from="麹町", to="市ヶ谷", line="有楽町線", distance=0.9, time=1),
    Distance(from="市ヶ谷", to="飯田橋", line="有楽町線", distance=1.1, time=2),
    Distance(from="飯田橋", to="江戸川橋", line="有楽町線", distance=1.6, time=3),
    Distance(from="江戸川橋", to="護国寺", line="有楽町線", distance=1.3, time=2),
    Distance(from="護国寺", to="東池袋", line="有楽町線", distance=1.1, time=2),
    Distance(from="東池袋", to="池袋", line="有楽町線", distance=2.0, time=2),
    Distance(from="池袋", to="要町", line="有楽町線", distance=1.2, time=2),
    Distance(from="要町", to="千川", line="有楽町線", distance=1.0, time=1),
    Distance(from="千川", to="小竹向原", line="有楽町線", distance=1.0, time=2),
    Distance(from="小竹向原", to="氷川台", line="有楽町線", distance=1.5, time=2),
    Distance(from="氷川台", to="平和台", line="有楽町線", distance=1.4, time=2),
    Distance(from="平和台", to="営団赤塚", line="有楽町線", distance=1.8, time=2),
    Distance(from="営団赤塚", to="営団成増", line="有楽町線", distance=1.5, time=2),
    Distance(from="営団成増", to="和光市", line="有楽町線", distance=2.1, time=3)
  )
}
